# Must unset the hold apt has on the version if you want to change it
K8S_VERSION: 1.28.2-1.1
#K8S_VERSION: 1.27.6-1.1
#K8S_VERSION: 1.26.9-1.1
#K8S_VERSION: 1.25.14-1.1

# Simply use the default port
K8S_API_SERVER_PORT: 6443

VIRTUAL_IP: "172.16.16.100"
VIRTUAL_IP_PORT: 6443

IP_HOST_LB1: 172.16.16.51
IP_HOST_LB2: 172.16.16.52
IP_HOST_CP1: 172.16.16.101
IP_HOST_CP2: 172.16.16.102
IP_HOST_CP3: 172.16.16.103
IP_HOST_W1: 172.16.16.201

POD_CIDR_FLANNEL: 10.244.0.0/16
POD_CIDR_CALICO: 192.168.0.0/16

VERSION_CALICO: "v3.26.1"

# Generate random string with:
#     openssl rand -base64 24
PASSWORD_KUBEADMIN: "kubeadmin"
PASSWORD_KEEPALIVED: "fW/19P0JzwNqIveyXfnhLXswVBUSFF4d3oMyVSi3g/U="
